### ISSUE TITLE
running problem with VS2013

### ISSUE THREAD

**Issue by arifle** [phdsky/ORBSLAM24Windows#4]
![pangolin_problem](https://user-images.githubusercontent.com/9264119/31598715-b68a7fe0-b281-11e7-9ca0-1d10af2f796b.png)
Hello,

The project is successfully compiled but I got a problem while running the routines.
RGB-D sensor mode, for example, gives an error in generating Pangolin viewer. It seems to be an error of the window creation but no further information is given by the compiler. The snapshot is attached here.

**Comment by phdsky** [comment]
Hello, arifle
I'm sorry I can't get any useful info from the snapshot; Did you tried mono_tum successfully? Maybe you can first disable the viewer thread then run to see whether the dump was caused by pangolin, Or you should try release mode. Thanks~

**Comment by arifle** [comment]
Hi. I tried as you said but don't have good news. I did it again Debug mode and made it after adding an implementation of vasprintf() into g2o project. Finally, ORB project and MonoTUM were built with no errors, and I tried running the second one but broke again at Pangolin::CreateWindow() for the first mapping which I think it is the 1st KeyFrame after initialization. BTW, my system is Windows 7 and has a VS2013. 
Well, it prompts that Pangolin.dll is required when running the project in Release mode (all of them were built in Release mode). Later, I got a lot of errors when trying to generate shared lib of Pangolin.

**Comment by arifle** [comment]
Hi. I got this kind of error after some attempts.

![error_mono](https://user-images.githubusercontent.com/9264119/32033076-0b72f72c-ba3d-11e7-8eff-4aaf59f9240b.png)
![error_mono2](https://user-images.githubusercontent.com/9264119/32033077-0bbbc510-ba3d-11e7-8ff5-9425b1664f8d.png)

**Comment by phdsky** [comment]
Hi.arifle 
I advise you to try release mode first, because I have tried to run orbslam2 in vs2013 debug mode serveal months ago, also got corruption like the same error, but in release mode it worked fine, and I have tried to find the reasons, list in below.
ORBSLAM is a muti-thread program, I have tried hardly through debug mode to find the actrual position where caused the corruption. Finally, I found when generating the first keyframe, and inserting keypoints to a **list** structure(the accurate line of code I can't remember), it's quite slow and have no respond! 
So I wrote an example code to test the list by inserting and deleting objects(10k~100k) in vs2013, it corrupted in debug mode but worked in release mode, so I guess it's vs2013 compiler’s optimization mechanism lead to this difference. 
If you want to run orbslam in debug mode, I suggust you to attempt in linux using Clion or kdevelop, because I also tried when inserting and deleting huge objects in list structure in debug mode, gcc worked fine, but before that you should modify the CMakeLists until it works.

**Comment by arifle** [comment]
Thanks man. I did it today with a new Pangolin in Release mode.
